version: "3"
services:
  placement:
    image: daprio/dapr:1.1.2
    command: [ "./placement","-port","50006" ]
  authService:
    image: withinboredom/magic-auth-service:0.1.0
    build:
      dockerfile: images/Dockerfile
      context: .
      target: server
    ports:
      - 80:80
      - 3500:3500
  authCaddy:
    image: withinboredom/magic-auth-caddy:0.1.0
    build:
      dockerfile: images/Dockerfile
      context: .
      target: caddy
    depends_on:
      - authService
    network_mode: service:authService
  authDapr:
    image: daprio/daprd:1.1.2
    command: [ "./daprd","-app-id","authService" ,"-app-port","80","-placement-host-address","placement:50006","-components-path","/components" ]
    volumes:
      - ./components-compose:/components
    depends_on:
      - authCaddy
    network_mode: service:authService
  redis:
    image: redis
